# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Dantis Elementorum
author: Dante Noguez
logo: logo.png
sphinx:
  config:
    html_show_copyright: false
    html_baseurl: 'https://dantenoguez.github.io/'
    bibtex_reference_style: author_year
    bibtex_bibfiles: references.bib
  extra_extensions:
    - sphinx_sitemap
    - sphinxcontrib.bibtex

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Define the name of the latex output file for PDF builds
latex:
  latex_engine: "xelatex"
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/DanteNoguez/Ensayos # Online location of your book
  path_to_book: ensayos  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  favicon: "logo.png"

